#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: #@ data.values.replicas
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: my-image:latest
        ports:
        - containerPort: 8080
